apiVersion: v1
kind: Pod
metadata:
  name: flask-app
spec:
  restartPolicy: Always
  containers:
  - name: flask
    image: jinny1/gfgwebimage
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 3
    resources:
      limits:
        memory: "800Mi"
        cpu: "800m"
      requests:
        memory: "600Mi"
        cpu: "400m"
