apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    dc: mumbai
    env: Prod
    team: operation
    manager: Manoj


spec:
  containers:
    - name: httpd
      image: httpd
      ports:
      - containerPort: 80
