apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
   name: my-manu-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mario-app
  minReplicas: 1
  maxReplicas: 14
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
