apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    dc: mumbai
    app: mongo
    env: prod
    team: manu-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
     name: mongodb
     labels:
       app: mongo
    spec:
      containers:
      - name: mongo-db
        image: mongo:5.0
        ports:
          - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
